add option to use a git repository when listing the advisory
wolfi-dev/wolfictl pull request #304
Opened 2023-07-21 09:33 UTC by cpanato

```
$ ./wolfictl advisory list -a https://github.com/wolfi-dev/advisories -p vim
INFO[0000] Cloning/updating repository wolfi-dev/advisories
vim: CVE-2023-1127: fixed (9.0.1378-r0)
vim: CVE-2023-1175: fixed (9.0.1378-r0)
vim: CVE-2023-1264: fixed (9.0.1392-r0)
vim: CVE-2023-1355: fixed (9.0.1402-r0)

```

2023-07-21 17:00 UTC, luhring requested changes
putting a hold just so we can discuss at our next opportunity 😃

2024-04-27 00:40 UTC, luhring commented
Howdy! Should we revisit this one?

2024-05-30 07:45 UTC, cpanato commented
@luhring is this something we still want? otherwise still fine to close it

2024-05-30 11:51 UTC, luhring commented
Okay we can close!

2024-05-30 11:51 UTC, closed without merging